---
services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    # Default command to run the ScalpStrategy with config_freqai.json in dry-run mode
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.dryrun.sqlite
      --config /freqtrade/user_data/config_freqai.json
      --strategy ScalpStrategy
